#define DYNEventSpecial
/* DSblock model generated by Dymola from Modelica model ExternalMedia.MyTests.TestFunc
 Dymola Version 2023 (64-bit), 2022-04-13 translated this at Thu Mar  2 12:53:15 2023

   */

#include <matrixop.h>
#include "matrixop.c"
/* Declaration of C-structs */
struct DymStruc0;
struct DymStruc0 {
  double  T_0member;
  double  a_0member;
  double  beta_0member;
  double  cp_0member;
  double  cv_0member;
  double  d_0member;
  double  ddhp_0member;
  double  ddph_0member;
  double  eta_0member;
  double  h_0member;
  double  kappa_0member;
  double  lambda_0member;
  double  p_0member;
  int  phase_0member;
  double  s_0member;
};
/* Prototypes for functions used in model */
#include "externalmedialib.h"
DYMOLA_STATIC struct DymStruc0  ExternalMedia_MyTests_setStatex_0ph_M(double  
  p0_0, double  h0_0, int  phase0_0, const char*  mediumName0_0, const char*  
  libraryName0_0, const char*  substanceName0_0);
/* Codes used in model */

/* Flattened Modelica model:

function ExternalMedia.MyTests.setState_ph
discrete input Real p(nominal = 100000.0, unit = "Pa", displayUnit = "bar", min = 0.0, max = 100000000.0) "pressure";
discrete input Real h(nominal = 1000000.0, unit = "J/kg", min = -10000000000.0, max = 10000000000.0) "specific enthalpy";
input Integer phase(min = 0.0, max = 2.0) "2 for two-phase, 1 for one-phase, 0 if not known";
input String mediumName "Name of the medium";
input String libraryName "Name of the external fluid property computation library";
input String substanceName;
discrete output ExternalMedia.MyTests.ThermodynamicState state;

external "C" equation
TwoPhaseMedium_setState_ph_C_impl(p, h, phase, state, mediumName, libraryName, substanceName) annotation(Include="#include \"externalmedialib.h\"", Library={"ExternalMediaLib"}, IncludeDirectory="modelica://ExternalMedia/Resources/Include", LibraryDirectory="modelica://ExternalMedia/Resources/Library");
end ExternalMedia.MyTests.setState_ph;

  */
DYMOLA_STATIC struct DymStruc0  ExternalMedia_MyTests_setStatex_0ph_M(double  
  p0_0, double  h0_0, int  phase0_0, const char*  mediumName0_0, const char*  
  libraryName0_0, const char*  substanceName0_0) {
  PushContext("ExternalMedia.MyTests.setState_ph")
  {
    /* Declare outputs and temporaries */
    struct DymStruc0  state0_0;
    state0_0.T_0member = 288.15;
    state0_0.a_0member = 1000;
    state0_0.beta_0member=0;
    state0_0.cp_0member = 1000.0;
    state0_0.cv_0member = 1000.0;
    state0_0.d_0member = 1;
    state0_0.ddhp_0member=0;
    state0_0.ddph_0member=0;
    state0_0.eta_0member = 0.001;
    state0_0.h_0member=0;
    state0_0.kappa_0member=0;
    state0_0.lambda_0member = 1;
    state0_0.p_0member = 100000.0;
    state0_0.phase_0member=0;
    state0_0.s_0member=0;
    /* Start of real code */
    {
      (TwoPhaseMedium_setState_ph_C_impl)(p0_0, h0_0, phase0_0, & state0_0, 
        mediumName0_0, libraryName0_0, substanceName0_0);
      }
    /* Output section */
    PopContext()
    return state0_0;
  }}
/* DSblock C-code: */

#define NX_    0
#define NX2_   0
#define NU_    0
#define NY_    0
#define NW_    15
#define NWP_   15
#define NP_    0
#define NPS_   0
#define ND_   0
#define NXP_   0
#define NInitial_   0
#define MAXAuxStr_   0
#define MAXAuxStrLen_   500
#define NHash1_ -1458560044
#define NHash2_ 1212985288
#define NHash3_ -202337923
#define NI_    0
#define NRelF_ 0
#define NRel_  0
#define NTim_  0
#define NSamp_ 0
#define NCons_ 0
#define NA_    0
#define SizePre_ 0
#define SizeEq_ 0
#define SizeDelay_ 0
#define QNLmax_ 0
#define MAXAux 0
#define NrDymolaTimers_ 0
#define NWhen_ 0
#define NCheckIf_ 0
#define NGlobalHelp_ 0
#define NGlobalHelpI_ 0
#ifndef NExternalObject_
#define NExternalObject_ 0
#endif
#include <moutil.c>
DYMOLA_STATIC unsigned int FMIClockValueReferences_[1]={0};
DYMOLA_STATIC unsigned int FMIClockFirstValueReferences_[1]={0};
PreNonAliasDef(0)
PreNonAliasDef(1)
PreNonAliasDef(2)
PreNonAliasDef(3)
PreNonAliasDef(4)
PreNonAliasDef(5)
#if !defined(DYM2CCUR)
 DYMOLA_STATIC const char*modelName="ExternalMedia.MyTests.TestFunc";
#endif
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={
#if defined(_WIN32) && !defined(_WIN64)

#elif defined(_WIN32) && defined(_WIN64)
"D:\\ExternalMedia 3.3.1\\Resources\\Library\\win64\\ExternalMediaLib.dll",
#endif
0};
DYMOLA_STATIC const char*default_dymosim_license_filename=
 "c:/users/dl411/appdata/roaming/dassaultsystemes/dymola/dymola.lic";
#include <dsblock1.c>

/* Define variable names. */

#define Sections_

TranslatedEquations
InitialSection

InitialSection
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
BoundParameterSection
BoundParameterConstantSection
{
  struct DymStruc0 dummy_DymStruc0;
  dummy_DymStruc0 = (PushModelContext(1,"ExternalMedia.MyTests.setState_ph(1000000.0, 200000.0, 0, \"My\", \"CoolProp\", \"REFPROP::CO2[0.7]&R125[0.3]|calc_transport=1|debug=true\")")
    ExternalMedia_MyTests_setStatex_0ph_M(1000000.0, 200000.0, 0, "My", 
    "CoolProp", "REFPROP::CO2[0.7]&R125[0.3]|calc_transport=1|debug=true"));
  DYNX(W_,0) = dummy_DymStruc0.T_0member;
  DYNX(W_,1) = dummy_DymStruc0.a_0member;
  DYNX(W_,2) = dummy_DymStruc0.beta_0member;
  DYNX(W_,3) = dummy_DymStruc0.cp_0member;
  DYNX(W_,4) = dummy_DymStruc0.cv_0member;
  DYNX(W_,5) = dummy_DymStruc0.d_0member;
  DYNX(W_,6) = dummy_DymStruc0.ddhp_0member;
  DYNX(W_,7) = dummy_DymStruc0.ddph_0member;
  DYNX(W_,8) = dummy_DymStruc0.eta_0member;
  DYNX(W_,9) = dummy_DymStruc0.h_0member;
  DYNX(W_,10) = dummy_DymStruc0.kappa_0member;
  DYNX(W_,11) = dummy_DymStruc0.lambda_0member;
  DYNX(W_,12) = dummy_DymStruc0.p_0member;
  DYNX(W_,13) = dummy_DymStruc0.phase_0member;
  DYNX(W_,14) = dummy_DymStruc0.s_0member;
PopModelContext();
}
BoundParameterSection
InitialSection
InitialStartSection
InitialSection
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
DefaultSection
InitializeData(0)
InitialSection
InitialSectionB
Init_=false;InitializeData(2);Init_=true;
EndInitialSection

OutputSection

DynamicsSection

AcceptedSection1

AcceptedSection2

DefaultSection
InitializeData(1)
EndTranslatedEquations

#include <dsblock6.c>

PreNonAliasNew(0)
StartNonAlias(0)
DeclareVariable("state.T", "temperature [K|degC]", 0, 288.15, 1.0,10000.0,300.0,\
0,513)
DeclareVariable("state.a", "velocity of sound [m/s]", 1, 1000, 0.0,100000.0,\
1000.0,0,513)
DeclareVariable("state.beta", "isobaric expansion coefficient [1/K]", 2, 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("state.cp", "specific heat capacity cp [J/(kg.K)]", 3, 1000.0, \
0.0,10000000.0,1000.0,0,513)
DeclareVariable("state.cv", "specific heat capacity cv [J/(kg.K)]", 4, 1000.0, \
0.0,10000000.0,1000.0,0,513)
DeclareVariable("state.d", "density [kg/m3|g/cm3]", 5, 1, 0.0,100000.0,1.0,0,513)
DeclareVariable("state.ddhp", "derivative of density wrt enthalpy at constant pressure [kg.s2/m5]",\
 6, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("state.ddph", "derivative of density wrt pressure at constant enthalpy [s2/m2]",\
 7, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("state.eta", "dynamic viscosity [Pa.s]", 8, 0.001, 0.0,\
100000000.0,0.001,0,513)
DeclareVariable("state.h", "specific enthalpy [J/kg]", 9, 0.0, -10000000000.0,\
10000000000.0,1000000.0,0,513)
DeclareVariable("state.kappa", "compressibility [1/Pa]", 10, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("state.lambda", "thermal conductivity [W/(m.K)]", 11, 1, 0.0,\
500.0,1.0,0,513)
DeclareVariable("state.p", "pressure [Pa|bar]", 12, 100000.0, 0.0,100000000.0,\
100000.0,0,513)
DeclareVariable("state.phase", "phase flag: 2 for two-phase, 1 for one-phase [:#(type=Integer)]",\
 13, 0, 0.0,2.0,0.0,0,517)
DeclareVariable("state.s", "specific entropy [J/(kg.K)]", 14, 0.0, -10000000.0,\
10000000.0,1000.0,0,513)
EndNonAlias(0)

#define DymolaHaveUpdateInitVars 1
#include <dsblock5.c>

DYMOLA_STATIC void UpdateInitVars(double*time, double* X_, double* XD_, double* U_, double* DP_, int IP_[], Dymola_bool LP_[], double* F_, double* Y_, double* W_, double QZ_[], double duser_[], int iuser_[], void*cuser_[],struct DYNInstanceData*did_,int initialCall) {
}
StartDataBlock
EndDataBlock
